version: '3.8'

services:
  web:
    image: node:16
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: npm start
    environment:
      DATABASE_URL: "file:/app/db.sqlite"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./db.sqlite:/data/db.sqlite

volumes:
  dbdata: